/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab6p2_emilianourtecho;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author emili
 */
public class EAGames extends javax.swing.JFrame {

    /**
     * Creates new form EAGames
     */
    public EAGames() {
        initComponents();
        pack();
        
        setLocationRelativeTo(null);
        setResizable(false);
        this.repaint();
        
    }

    
    public boolean UsuarioExistente(String usuario){
        for (int i = 0; i < user.size(); i++) {
            if (usuario.equals(user.get(i).getNombreU())) {
                return true;
            }
        }
        return false;
    }
    public boolean ConfirmarFecha(String fecha){
        int fechaInt = Integer.parseInt(fecha);
        int anio = (2023 - fechaInt);
        if (fecha.matches("\\d{4}")) {
            return false;
        }        
        
        return anio > 12;
    }
    public boolean UsuarioEntrar(String nombre, String password){
        String name = tf_nombreUsuario.getText();
        String pass = pf_password.getText();
        for (User user1 : user) {
            if (name.equals(user1.getNombreU()) && pass.equals(user1.getPassword())) {
                return true;
            }
        }
        return false;
    }
    public boolean AdminEntrar(String nombre, String password){
        String name = tf_nombreUsuario1.getText();
        String pass = pf_password1.getText();
        for (Admin adm : admin) {
            if (name.equals(adm.getNombreU()) && pass.equals(adm.getPassword())) {
                return true;
            }
        }
        return false;
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        d_crearCuenta = new javax.swing.JDialog();
        p_crearCuentaU = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        tf_crearUsuario = new javax.swing.JTextField();
        tf_nombreOG = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        tf_correo = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        tf_crearPassword = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        cb_pais = new javax.swing.JComboBox<>();
        ff_fechaNacimiento = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        b_regresar = new javax.swing.JButton();
        b_crear = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        d_pagina = new javax.swing.JDialog();
        tp_main = new javax.swing.JTabbedPane();
        p_jugadores = new javax.swing.JPanel();
        tp_jugador = new javax.swing.JTabbedPane();
        p_cj = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        p_bj = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        p_mj = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        p_ej = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        p_compra = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        p_ventas = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        p_instMV = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel20 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        d_Admin = new javax.swing.JDialog();
        jPanel21 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        d_crearAdmin = new javax.swing.JDialog();
        p_crearCuentaA = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        tf_crearUsuario1 = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        tf_correo1 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        tf_crearPassword1 = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        cb_pais1 = new javax.swing.JComboBox<>();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        ff_fechaNacimiento1 = new javax.swing.JFormattedTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        b_crear1 = new javax.swing.JButton();
        b_regresar1 = new javax.swing.JButton();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        d_iniciarAdmin = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        tf_nombreUsuario1 = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        pf_password1 = new javax.swing.JPasswordField();
        b_iniciarSesionA = new javax.swing.JButton();
        jSeparator19 = new javax.swing.JSeparator();
        b_entrarUser = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        b_crearCuentaA = new javax.swing.JButton();
        p_iniciarSesion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        tf_nombreUsuario = new javax.swing.JTextField();
        pf_password = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        b_crearCuenta = new javax.swing.JButton();
        b_iniciarSesion = new javax.swing.JButton();
        b_entrarAdmin = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();

        d_crearCuenta.setPreferredSize(new java.awt.Dimension(700, 400));
        d_crearCuenta.setSize(new java.awt.Dimension(700, 400));
        d_crearCuenta.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_crearCuentaU.setBackground(new java.awt.Color(255, 255, 255));
        p_crearCuentaU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p_crearCuentaU.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCuentaU.setMinimumSize(new java.awt.Dimension(700, 400));
        p_crearCuentaU.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Broadway", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Usuario");
        p_crearCuentaU.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 90, -1));

        jLabel6.setFont(new java.awt.Font("Broadway", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nombre");
        p_crearCuentaU.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 70, -1));

        jLabel7.setFont(new java.awt.Font("Broadway", 2, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Como Usuario");
        p_crearCuentaU.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 230, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCuentaU.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 360, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        p_crearCuentaU.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 20, 330));

        tf_crearUsuario.setBackground(new java.awt.Color(255, 255, 255));
        tf_crearUsuario.setFont(new java.awt.Font("OCR A Extended", 1, 10)); // NOI18N
        tf_crearUsuario.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCuentaU.add(tf_crearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 320, -1));

        tf_nombreOG.setBackground(new java.awt.Color(255, 255, 255));
        tf_nombreOG.setFont(new java.awt.Font("OCR A Extended", 1, 10)); // NOI18N
        tf_nombreOG.setForeground(new java.awt.Color(0, 0, 0));
        tf_nombreOG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreOGActionPerformed(evt);
            }
        });
        p_crearCuentaU.add(tf_nombreOG, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 320, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCuentaU.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 360, 10));

        jLabel8.setFont(new java.awt.Font("Broadway", 2, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Su Correo Electronico");
        p_crearCuentaU.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 170, -1));

        tf_correo.setBackground(new java.awt.Color(255, 255, 255));
        tf_correo.setFont(new java.awt.Font("OCR A Extended", 1, 10)); // NOI18N
        tf_correo.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCuentaU.add(tf_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 320, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCuentaU.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 360, 10));

        jLabel9.setFont(new java.awt.Font("Broadway", 2, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Password");
        p_crearCuentaU.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 90, -1));

        tf_crearPassword.setBackground(new java.awt.Color(255, 255, 255));
        tf_crearPassword.setFont(new java.awt.Font("OCR A Extended", 1, 10)); // NOI18N
        tf_crearPassword.setForeground(new java.awt.Color(0, 0, 0));
        tf_crearPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_crearPasswordActionPerformed(evt);
            }
        });
        p_crearCuentaU.add(tf_crearPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 320, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCuentaU.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 360, 10));

        jLabel11.setFont(new java.awt.Font("Broadway", 2, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Pais de Residencia");
        p_crearCuentaU.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 150, -1));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCuentaU.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 360, 10));

        cb_pais.setBackground(new java.awt.Color(255, 255, 255));
        cb_pais.setFont(new java.awt.Font("OCR A Extended", 1, 10)); // NOI18N
        cb_pais.setForeground(new java.awt.Color(0, 0, 0));
        cb_pais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estados Unidos", "Japan", "Italia", "Alemania", "Francia", "UK", "Sweden" }));
        cb_pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_paisActionPerformed(evt);
            }
        });
        p_crearCuentaU.add(cb_pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 320, -1));

        ff_fechaNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        ff_fechaNacimiento.setForeground(new java.awt.Color(0, 0, 0));
        ff_fechaNacimiento.setFont(new java.awt.Font("OCR A Extended", 1, 10)); // NOI18N
        p_crearCuentaU.add(ff_fechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 330, -1));

        jLabel12.setFont(new java.awt.Font("Broadway", 2, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Ingrese su año de Nacimiento");
        p_crearCuentaU.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 230, -1));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCuentaU.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 360, 10));

        b_regresar.setFont(new java.awt.Font("Broadway", 1, 18)); // NOI18N
        b_regresar.setForeground(new java.awt.Color(0, 0, 0));
        b_regresar.setText("Regresar");
        b_regresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_regresar.setContentAreaFilled(false);
        b_regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_regresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_regresarMouseExited(evt);
            }
        });
        b_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_regresarActionPerformed(evt);
            }
        });
        p_crearCuentaU.add(b_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 100, 20));

        b_crear.setFont(new java.awt.Font("Broadway", 1, 18)); // NOI18N
        b_crear.setForeground(new java.awt.Color(0, 0, 0));
        b_crear.setText("Crear");
        b_crear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_crear.setContentAreaFilled(false);
        b_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_crearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_crearMouseExited(evt);
            }
        });
        b_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_crearActionPerformed(evt);
            }
        });
        p_crearCuentaU.add(b_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 70, 20));

        jLabel20.setFont(new java.awt.Font("Broadway", 2, 30)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("CREAR CUENTA");
        p_crearCuentaU.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 260, -1));

        d_crearCuenta.getContentPane().add(p_crearCuentaU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        d_pagina.setMinimumSize(new java.awt.Dimension(700, 400));
        d_pagina.setPreferredSize(new java.awt.Dimension(700, 400));
        d_pagina.setSize(new java.awt.Dimension(700, 400));
        d_pagina.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tp_main.setBackground(new java.awt.Color(255, 255, 255));
        tp_main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tp_main.setForeground(new java.awt.Color(0, 0, 0));
        tp_main.setFont(new java.awt.Font("Broadway", 0, 12)); // NOI18N

        p_jugadores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tp_jugador.setBackground(new java.awt.Color(255, 255, 255));
        tp_jugador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tp_jugador.setForeground(new java.awt.Color(0, 0, 0));
        tp_jugador.setFont(new java.awt.Font("Broadway", 0, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout p_cjLayout = new javax.swing.GroupLayout(p_cj);
        p_cj.setLayout(p_cjLayout);
        p_cjLayout.setHorizontalGroup(
            p_cjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        p_cjLayout.setVerticalGroup(
            p_cjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tp_jugador.addTab("Crear Jugador", p_cj);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout p_bjLayout = new javax.swing.GroupLayout(p_bj);
        p_bj.setLayout(p_bjLayout);
        p_bjLayout.setHorizontalGroup(
            p_bjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        p_bjLayout.setVerticalGroup(
            p_bjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tp_jugador.addTab("Buscar Jugador", p_bj);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout p_mjLayout = new javax.swing.GroupLayout(p_mj);
        p_mj.setLayout(p_mjLayout);
        p_mjLayout.setHorizontalGroup(
            p_mjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        p_mjLayout.setVerticalGroup(
            p_mjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tp_jugador.addTab("Modificar Jugador", p_mj);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout p_ejLayout = new javax.swing.GroupLayout(p_ej);
        p_ej.setLayout(p_ejLayout);
        p_ejLayout.setHorizontalGroup(
            p_ejLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        p_ejLayout.setVerticalGroup(
            p_ejLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tp_jugador.addTab("Eliminar Jugador", p_ej);

        p_jugadores.add(tp_jugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 79, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        p_jugadores.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 370));

        tp_main.addTab("Jugadores", p_jugadores);

        p_compra.setEnabled(false);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel18.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout p_compraLayout = new javax.swing.GroupLayout(p_compra);
        p_compra.setLayout(p_compraLayout);
        p_compraLayout.setHorizontalGroup(
            p_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(p_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(p_compraLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        p_compraLayout.setVerticalGroup(
            p_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
            .addGroup(p_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(p_compraLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tp_main.addTab("Compra", p_compra);

        p_ventas.setEnabled(false);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout p_ventasLayout = new javax.swing.GroupLayout(p_ventas);
        p_ventas.setLayout(p_ventasLayout);
        p_ventasLayout.setHorizontalGroup(
            p_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(p_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(p_ventasLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        p_ventasLayout.setVerticalGroup(
            p_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
            .addGroup(p_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(p_ventasLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tp_main.addTab("Ventas", p_ventas);

        p_instMV.setEnabled(false);
        p_instMV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setBackground(new java.awt.Color(255, 255, 255));
        jList1.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        jList1.setForeground(new java.awt.Color(0, 0, 0));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        p_instMV.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 6, 290, 355));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel20.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        p_instMV.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 370));

        tp_main.addTab("Instalacion de Mejoras Visuales", p_instMV);

        d_pagina.getContentPane().add(tp_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 400));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        d_pagina.getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 400));

        d_Admin.setMinimumSize(new java.awt.Dimension(700, 400));
        d_Admin.setSize(new java.awt.Dimension(700, 400));
        d_Admin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel21.setForeground(new java.awt.Color(0, 0, 0));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Crear Carro", jPanel22);

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Modificar Carro", jPanel23);

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Listar Carro", jPanel24);

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Modificar Carro", jPanel25);

        jPanel21.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        d_Admin.getContentPane().add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        d_crearAdmin.setMinimumSize(new java.awt.Dimension(700, 400));
        d_crearAdmin.setPreferredSize(new java.awt.Dimension(700, 400));
        d_crearAdmin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_crearCuentaA.setBackground(new java.awt.Color(255, 255, 255));
        p_crearCuentaA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p_crearCuentaA.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCuentaA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Broadway", 2, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Usuario");
        p_crearCuentaA.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 90, -1));

        tf_crearUsuario1.setBackground(new java.awt.Color(255, 255, 255));
        tf_crearUsuario1.setFont(new java.awt.Font("OCR A Extended", 1, 10)); // NOI18N
        tf_crearUsuario1.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCuentaA.add(tf_crearUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 320, -1));

        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCuentaA.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 360, 10));

        jLabel14.setFont(new java.awt.Font("Broadway", 2, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Su Correo Electronico");
        p_crearCuentaA.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 170, -1));

        tf_correo1.setBackground(new java.awt.Color(255, 255, 255));
        tf_correo1.setFont(new java.awt.Font("OCR A Extended", 1, 10)); // NOI18N
        tf_correo1.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCuentaA.add(tf_correo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 320, -1));

        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCuentaA.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 360, 10));

        jLabel15.setFont(new java.awt.Font("Broadway", 2, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Password");
        p_crearCuentaA.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 90, -1));

        tf_crearPassword1.setBackground(new java.awt.Color(255, 255, 255));
        tf_crearPassword1.setFont(new java.awt.Font("OCR A Extended", 1, 10)); // NOI18N
        tf_crearPassword1.setForeground(new java.awt.Color(0, 0, 0));
        tf_crearPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_crearPassword1ActionPerformed(evt);
            }
        });
        p_crearCuentaA.add(tf_crearPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 320, -1));

        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCuentaA.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 360, 10));

        jLabel16.setFont(new java.awt.Font("Broadway", 2, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Pais de Residencia");
        p_crearCuentaA.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 150, -1));

        cb_pais1.setBackground(new java.awt.Color(255, 255, 255));
        cb_pais1.setFont(new java.awt.Font("OCR A Extended", 1, 10)); // NOI18N
        cb_pais1.setForeground(new java.awt.Color(0, 0, 0));
        cb_pais1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estados Unidos", "Japan", "Italia", "Alemania", "Francia", "UK", "Sweden" }));
        p_crearCuentaA.add(cb_pais1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 320, -1));

        jSeparator15.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCuentaA.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 360, 10));

        jLabel17.setFont(new java.awt.Font("Broadway", 2, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Ingrese su año de Nacimiento");
        p_crearCuentaA.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 230, -1));

        ff_fechaNacimiento1.setBackground(new java.awt.Color(255, 255, 255));
        ff_fechaNacimiento1.setForeground(new java.awt.Color(0, 0, 0));
        ff_fechaNacimiento1.setFont(new java.awt.Font("OCR A Extended", 1, 10)); // NOI18N
        p_crearCuentaA.add(ff_fechaNacimiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 330, -1));

        jSeparator16.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCuentaA.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 360, 10));

        jLabel18.setFont(new java.awt.Font("Broadway", 2, 30)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Como Admin");
        p_crearCuentaA.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 230, -1));

        b_crear1.setFont(new java.awt.Font("Broadway", 1, 18)); // NOI18N
        b_crear1.setForeground(new java.awt.Color(0, 0, 0));
        b_crear1.setText("Crear");
        b_crear1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_crear1.setContentAreaFilled(false);
        b_crear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_crear1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_crear1MouseExited(evt);
            }
        });
        b_crear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_crear1ActionPerformed(evt);
            }
        });
        p_crearCuentaA.add(b_crear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 70, 20));

        b_regresar1.setFont(new java.awt.Font("Broadway", 1, 18)); // NOI18N
        b_regresar1.setForeground(new java.awt.Color(0, 0, 0));
        b_regresar1.setText("Regresar");
        b_regresar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_regresar1.setContentAreaFilled(false);
        b_regresar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_regresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_regresar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_regresar1MouseExited(evt);
            }
        });
        b_regresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_regresar1ActionPerformed(evt);
            }
        });
        p_crearCuentaA.add(b_regresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 100, 20));

        jSeparator17.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator17.setOrientation(javax.swing.SwingConstants.VERTICAL);
        p_crearCuentaA.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 20, 330));

        jLabel19.setFont(new java.awt.Font("Broadway", 2, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("CREAR CUENTA");
        p_crearCuentaA.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 260, -1));

        d_crearAdmin.getContentPane().add(p_crearCuentaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        d_iniciarAdmin.setMinimumSize(new java.awt.Dimension(700, 400));
        d_iniciarAdmin.setSize(new java.awt.Dimension(700, 400));
        d_iniciarAdmin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Broadway", 2, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Iniciar Sesión COMO ADMIN");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 580, -1));

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 440, 10));

        jLabel21.setFont(new java.awt.Font("Broadway", 2, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Usuario");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 70, -1));

        tf_nombreUsuario1.setBackground(new java.awt.Color(255, 255, 255));
        tf_nombreUsuario1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(tf_nombreUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 330, -1));

        jSeparator18.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 400, 10));

        jLabel22.setFont(new java.awt.Font("Broadway", 2, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Password");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 80, -1));

        pf_password1.setBackground(new java.awt.Color(255, 255, 255));
        pf_password1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(pf_password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 330, -1));

        b_iniciarSesionA.setFont(new java.awt.Font("Broadway", 0, 14)); // NOI18N
        b_iniciarSesionA.setForeground(new java.awt.Color(0, 0, 0));
        b_iniciarSesionA.setText("Iniciar Sesion");
        b_iniciarSesionA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_iniciarSesionA.setContentAreaFilled(false);
        b_iniciarSesionA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_iniciarSesionA.setFocusPainted(false);
        b_iniciarSesionA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_iniciarSesionAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_iniciarSesionAMouseExited(evt);
            }
        });
        b_iniciarSesionA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_iniciarSesionAActionPerformed(evt);
            }
        });
        jPanel1.add(b_iniciarSesionA, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 120, -1));

        jSeparator19.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 10, 40));

        b_entrarUser.setFont(new java.awt.Font("Broadway", 0, 14)); // NOI18N
        b_entrarUser.setForeground(new java.awt.Color(0, 0, 0));
        b_entrarUser.setText("Entrar Como USER");
        b_entrarUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_entrarUser.setContentAreaFilled(false);
        b_entrarUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_entrarUser.setFocusPainted(false);
        b_entrarUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_entrarUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_entrarUserMouseExited(evt);
            }
        });
        b_entrarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_entrarUserActionPerformed(evt);
            }
        });
        jPanel1.add(b_entrarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 170, -1));

        jLabel23.setFont(new java.awt.Font("Broadway", 0, 10)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Si aun no tiene una cuenta entonces haga");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 230, -1));

        b_crearCuentaA.setFont(new java.awt.Font("Broadway", 0, 10)); // NOI18N
        b_crearCuentaA.setForeground(new java.awt.Color(102, 102, 102));
        b_crearCuentaA.setText("CLICK AQUI");
        b_crearCuentaA.setBorder(null);
        b_crearCuentaA.setBorderPainted(false);
        b_crearCuentaA.setContentAreaFilled(false);
        b_crearCuentaA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_crearCuentaA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_crearCuentaAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_crearCuentaAMouseExited(evt);
            }
        });
        b_crearCuentaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_crearCuentaAActionPerformed(evt);
            }
        });
        jPanel1.add(b_crearCuentaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        d_iniciarAdmin.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_iniciarSesion.setBackground(new java.awt.Color(255, 255, 255));
        p_iniciarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p_iniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        p_iniciarSesion.setMinimumSize(new java.awt.Dimension(700, 400));
        p_iniciarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Broadway", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Si aun no tiene una cuenta entonces haga");
        p_iniciarSesion.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 230, -1));

        jLabel2.setFont(new java.awt.Font("Broadway", 2, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Iniciar Sesión COMO USUARIO");
        p_iniciarSesion.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 580, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        p_iniciarSesion.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 400, 10));

        jLabel3.setFont(new java.awt.Font("Broadway", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Usuario");
        p_iniciarSesion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 70, -1));

        tf_nombreUsuario.setBackground(new java.awt.Color(255, 255, 255));
        tf_nombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        p_iniciarSesion.add(tf_nombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 330, -1));

        pf_password.setBackground(new java.awt.Color(255, 255, 255));
        pf_password.setForeground(new java.awt.Color(0, 0, 0));
        p_iniciarSesion.add(pf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 330, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        p_iniciarSesion.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 440, 10));

        jLabel4.setFont(new java.awt.Font("Broadway", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Password");
        p_iniciarSesion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 80, -1));

        b_crearCuenta.setFont(new java.awt.Font("Broadway", 0, 10)); // NOI18N
        b_crearCuenta.setForeground(new java.awt.Color(102, 102, 102));
        b_crearCuenta.setText("CLICK AQUI");
        b_crearCuenta.setBorder(null);
        b_crearCuenta.setBorderPainted(false);
        b_crearCuenta.setContentAreaFilled(false);
        b_crearCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_crearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_crearCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_crearCuentaMouseExited(evt);
            }
        });
        b_crearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_crearCuentaActionPerformed(evt);
            }
        });
        p_iniciarSesion.add(b_crearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        b_iniciarSesion.setFont(new java.awt.Font("Broadway", 0, 14)); // NOI18N
        b_iniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        b_iniciarSesion.setText("Iniciar Sesion");
        b_iniciarSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_iniciarSesion.setContentAreaFilled(false);
        b_iniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_iniciarSesion.setFocusPainted(false);
        b_iniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_iniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_iniciarSesionMouseExited(evt);
            }
        });
        b_iniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_iniciarSesionActionPerformed(evt);
            }
        });
        p_iniciarSesion.add(b_iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 120, -1));

        b_entrarAdmin.setFont(new java.awt.Font("Broadway", 0, 14)); // NOI18N
        b_entrarAdmin.setForeground(new java.awt.Color(0, 0, 0));
        b_entrarAdmin.setText("Entrar Como Admin");
        b_entrarAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_entrarAdmin.setContentAreaFilled(false);
        b_entrarAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_entrarAdmin.setFocusPainted(false);
        b_entrarAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_entrarAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_entrarAdminMouseExited(evt);
            }
        });
        b_entrarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_entrarAdminActionPerformed(evt);
            }
        });
        p_iniciarSesion.add(b_entrarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 170, -1));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        p_iniciarSesion.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 10, 40));

        getContentPane().add(p_iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_crearCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_crearCuentaMouseEntered
        b_crearCuenta.setBounds(430, 350, 66, 17);
        b_crearCuenta.setForeground(Color.black);
    }//GEN-LAST:event_b_crearCuentaMouseEntered

    private void b_crearCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_crearCuentaMouseExited
        b_crearCuenta.setBounds(430, 350, 62, 13);
        b_crearCuenta.setForeground(Color.gray);
    }//GEN-LAST:event_b_crearCuentaMouseExited

    private void b_crearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_crearCuentaActionPerformed
        d_crearCuenta.pack();
        d_crearCuenta.setLocationRelativeTo(this);
        d_crearCuenta.setVisible(true);
        
    }//GEN-LAST:event_b_crearCuentaActionPerformed

    private void tf_crearPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_crearPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_crearPasswordActionPerformed

    private void tf_nombreOGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreOGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreOGActionPerformed

    private void b_regresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_regresarMouseEntered
        b_regresar.setForeground(Color.gray);
        b_regresar.setBorderPainted(false);
    }//GEN-LAST:event_b_regresarMouseEntered

    private void b_regresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_regresarMouseExited
        b_regresar.setForeground(Color.black);
        b_regresar.setBorderPainted(true);
    }//GEN-LAST:event_b_regresarMouseExited

    private void b_crearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_crearMouseEntered
        b_crear.setForeground(Color.gray);
        b_crear.setBorderPainted(false);
    }//GEN-LAST:event_b_crearMouseEntered

    private void b_crearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_crearMouseExited
        b_crear.setForeground(Color.black);
        b_crear.setBorderPainted(true);
    }//GEN-LAST:event_b_crearMouseExited

    private void b_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_regresarActionPerformed
        
        d_crearCuenta.setLocationRelativeTo(null);
        d_crearCuenta.setVisible(false);        
    }//GEN-LAST:event_b_regresarActionPerformed

    private void b_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_crearActionPerformed
        String nombreOG = tf_nombreOG.getText();
        String crearUsuario = tf_crearUsuario.getText();
        String correo = tf_correo.getText();
        String password = tf_crearPassword.getText();
        String fecha = ff_fechaNacimiento.getText();
        
        if (nombreOG.isEmpty() || crearUsuario.isEmpty() || correo.isEmpty()
                || password.isEmpty() || fecha.isEmpty() || cb_pais.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Hay mas de dos casillas vacias, por favor llenelas todas las casillas");
            
        }else{
            if (nombreOG.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No ha ingresado su nombre aun");                
            }else if(crearUsuario.isEmpty()){
            JOptionPane.showMessageDialog(this, "No ha ingresado su nombre de USUARIO aun");                                
            }else if(correo.isEmpty()){
            JOptionPane.showMessageDialog(this, "No ha ingresado su correo electronico aun");                                
            }else if(password.isEmpty()){
            JOptionPane.showMessageDialog(this, "No ha ingresado su PASSWORD aun");                                
            }else if(fecha.isEmpty()){
            JOptionPane.showMessageDialog(this, "No ha ingresado su fecha de nacimiento aun");                                
            }else if(cb_pais.getSelectedItem() == null){
            JOptionPane.showMessageDialog(this, "No ha ingresado su pais de residencia, seleccione una"); 
            }else{
                if (UsuarioExistente(crearUsuario)) {
                    JOptionPane.showMessageDialog(this, "El nombre ya existe, escriba otro porfavor");                    
                }else if(!ConfirmarFecha(fecha)){
                    JOptionPane.showMessageDialog(this, "Debes ser mayor de 12 años para tener una cuenta");
                }else if(!password.matches("^(?=.*[A-Z])(?=.*[a-z])(?=.*\\W).*$")){ // Osman nos enseno esto.
                    JOptionPane.showMessageDialog(this, "La password debe contener una mayuscula, minuscula y un caracter especial");
                }else{
                    String pais = (String) cb_pais.getSelectedItem();
                    User u = new User(crearUsuario, nombreOG, correo, pais, fecha, password);
                    user.add(u);
                    d_crearCuenta.setLocationRelativeTo(null);
                    d_crearCuenta.setVisible(false); 
                    
                }             
            }
        }                
    }//GEN-LAST:event_b_crearActionPerformed

    private void b_iniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_iniciarSesionMouseEntered
        b_crear.setForeground(Color.gray);
        b_crear.setBorderPainted(false);        
    }//GEN-LAST:event_b_iniciarSesionMouseEntered

    private void b_iniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_iniciarSesionMouseExited
        b_crear.setForeground(Color.black);
        b_crear.setBorderPainted(true);        
    }//GEN-LAST:event_b_iniciarSesionMouseExited

    private void b_iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_iniciarSesionActionPerformed
        String nombreU = tf_nombreUsuario.getText();
        String passwords = pf_password.getText();
        if (UsuarioEntrar(nombreU, passwords)) {
            d_pagina.pack();
            d_pagina.setLocationRelativeTo(this);
            d_pagina.setVisible(true);                
        }else{
            JOptionPane.showMessageDialog(this, "Nombre de usuario o password incorrecta");
        }
    }//GEN-LAST:event_b_iniciarSesionActionPerformed

    private void b_entrarAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_entrarAdminMouseEntered
        b_crear.setForeground(Color.gray);
        b_crear.setBorderPainted(false);               
    }//GEN-LAST:event_b_entrarAdminMouseEntered

    private void b_entrarAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_entrarAdminMouseExited
        b_crear.setForeground(Color.black);
        b_crear.setBorderPainted(true);                
    }//GEN-LAST:event_b_entrarAdminMouseExited

    private void b_entrarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_entrarAdminActionPerformed
        d_iniciarAdmin.pack();
        d_iniciarAdmin.setLocationRelativeTo(this);
        d_iniciarAdmin.setVisible(true);
        p_iniciarSesion.setVisible(false);
    }//GEN-LAST:event_b_entrarAdminActionPerformed

    private void tf_crearPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_crearPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_crearPassword1ActionPerformed

    private void b_crear1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_crear1MouseEntered
        b_crear.setForeground(Color.gray);
        b_crear.setBorderPainted(false);
    }//GEN-LAST:event_b_crear1MouseEntered

    private void b_crear1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_crear1MouseExited
        b_crear.setForeground(Color.black);
        b_crear.setBorderPainted(true);
    }//GEN-LAST:event_b_crear1MouseExited

    private void b_crear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_crear1ActionPerformed
        String crearUsuario = tf_crearUsuario1.getText();
        String correo = tf_correo1.getText();
        String password = tf_crearPassword1.getText();
        String fecha = ff_fechaNacimiento1.getText();
        
        if (crearUsuario.isEmpty() || correo.isEmpty()
                || password.isEmpty() || fecha.isEmpty() || cb_pais.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Hay mas de dos casillas vacias, por favor llenelas todas las casillas");
            
        }else{
            if(crearUsuario.isEmpty()){
            JOptionPane.showMessageDialog(this, "No ha ingresado su nombre de USUARIO aun");                                
            }else if(correo.isEmpty()){
            JOptionPane.showMessageDialog(this, "No ha ingresado su correo electronico aun");                                
            }else if(password.isEmpty()){
            JOptionPane.showMessageDialog(this, "No ha ingresado su PASSWORD aun");                                
            }else if(fecha.isEmpty()){
            JOptionPane.showMessageDialog(this, "No ha ingresado su fecha de nacimiento aun");                                
            }else if(cb_pais1.getSelectedItem() == null){
            JOptionPane.showMessageDialog(this, "No ha ingresado su pais de residencia, seleccione una"); 
            }else{
                if (UsuarioExistente(crearUsuario)) {
                    JOptionPane.showMessageDialog(this, "El nombre ya existe, escriba otro porfavor");                    
                }else if(!ConfirmarFecha(fecha)){
                    JOptionPane.showMessageDialog(this, "Debes ser mayor de 12 años para tener una cuenta");
                }else if(!password.matches("^(?=.*[A-Z])(?=.*[a-z])(?=.*\\W).*$")){
                    JOptionPane.showMessageDialog(this, "La password debe contener una mayuscula, minuscula y un caracter especial");
                }else{
                    String pais = (String) cb_pais1.getSelectedItem();
                    Admin a = new Admin(crearUsuario, correo, password, fecha, pais);
                    admin.add(a);
                    d_crearAdmin.setLocationRelativeTo(null);
                    d_crearAdmin.setVisible(false); 
                }             
            }
        }
    }//GEN-LAST:event_b_crear1ActionPerformed

    private void b_regresar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_regresar1MouseEntered
        b_crear.setForeground(Color.gray);
        b_crear.setBorderPainted(false);        
    }//GEN-LAST:event_b_regresar1MouseEntered

    private void b_regresar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_regresar1MouseExited
        b_crear.setForeground(Color.black);
        b_crear.setBorderPainted(true);        
    }//GEN-LAST:event_b_regresar1MouseExited

    private void b_regresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_regresar1ActionPerformed
        d_crearAdmin.setLocationRelativeTo(null);
        d_crearAdmin.setVisible(false);
    }//GEN-LAST:event_b_regresar1ActionPerformed

    private void cb_paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_paisActionPerformed
        
    }//GEN-LAST:event_cb_paisActionPerformed

    private void b_iniciarSesionAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_iniciarSesionAMouseEntered
        b_crear.setForeground(Color.gray);
        b_crear.setBorderPainted(false);        
    }//GEN-LAST:event_b_iniciarSesionAMouseEntered

    private void b_iniciarSesionAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_iniciarSesionAMouseExited
        b_crear.setForeground(Color.black);
        b_crear.setBorderPainted(true);        
    }//GEN-LAST:event_b_iniciarSesionAMouseExited

    private void b_iniciarSesionAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_iniciarSesionAActionPerformed
        String nombreU = tf_nombreUsuario1.getText();
        String passwords = pf_password1.getText();
        if (AdminEntrar(nombreU, passwords)) {
            d_Admin.pack();
            d_Admin.setLocationRelativeTo(this);
            d_Admin.setVisible(true);                
        }else{
            JOptionPane.showMessageDialog(this, "Nombre de usuario o password incorrecta");
        }        
    }//GEN-LAST:event_b_iniciarSesionAActionPerformed

    private void b_entrarUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_entrarUserMouseEntered
        b_crear.setForeground(Color.gray);
        b_crear.setBorderPainted(false);        
    }//GEN-LAST:event_b_entrarUserMouseEntered

    private void b_entrarUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_entrarUserMouseExited
        b_crear.setForeground(Color.black);
        b_crear.setBorderPainted(true);        
    }//GEN-LAST:event_b_entrarUserMouseExited

    private void b_entrarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_entrarUserActionPerformed
        d_iniciarAdmin.setLocationRelativeTo(null);
        d_iniciarAdmin.setVisible(false);
        p_iniciarSesion.setVisible(true);
    }//GEN-LAST:event_b_entrarUserActionPerformed

    private void b_crearCuentaAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_crearCuentaAMouseEntered
        b_crearCuenta.setBounds(430, 350, 66, 17);
        b_crearCuenta.setForeground(Color.black);        
    }//GEN-LAST:event_b_crearCuentaAMouseEntered

    private void b_crearCuentaAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_crearCuentaAMouseExited
        b_crearCuenta.setBounds(430, 350, 62, 13);
        b_crearCuenta.setForeground(Color.gray);        
    }//GEN-LAST:event_b_crearCuentaAMouseExited

    private void b_crearCuentaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_crearCuentaAActionPerformed
        d_crearAdmin.pack();
        d_crearAdmin.setLocationRelativeTo(this);
        d_crearAdmin.setVisible(true);
    }//GEN-LAST:event_b_crearCuentaAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EAGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EAGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EAGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EAGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EAGames().setVisible(true);
            }
        });
    }
    
    ArrayList<User> user = new ArrayList();
    ArrayList<Admin> admin = new ArrayList();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_crear;
    private javax.swing.JButton b_crear1;
    private javax.swing.JButton b_crearCuenta;
    private javax.swing.JButton b_crearCuentaA;
    private javax.swing.JButton b_entrarAdmin;
    private javax.swing.JButton b_entrarUser;
    private javax.swing.JButton b_iniciarSesion;
    private javax.swing.JButton b_iniciarSesionA;
    private javax.swing.JButton b_regresar;
    private javax.swing.JButton b_regresar1;
    private javax.swing.JComboBox<String> cb_pais;
    private javax.swing.JComboBox<String> cb_pais1;
    private javax.swing.JDialog d_Admin;
    private javax.swing.JDialog d_crearAdmin;
    private javax.swing.JDialog d_crearCuenta;
    private javax.swing.JDialog d_iniciarAdmin;
    private javax.swing.JDialog d_pagina;
    private javax.swing.JFormattedTextField ff_fechaNacimiento;
    private javax.swing.JFormattedTextField ff_fechaNacimiento1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel p_bj;
    private javax.swing.JPanel p_cj;
    private javax.swing.JPanel p_compra;
    private javax.swing.JPanel p_crearCuentaA;
    private javax.swing.JPanel p_crearCuentaU;
    private javax.swing.JPanel p_ej;
    private javax.swing.JPanel p_iniciarSesion;
    private javax.swing.JPanel p_instMV;
    private javax.swing.JPanel p_jugadores;
    private javax.swing.JPanel p_mj;
    private javax.swing.JPanel p_ventas;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JPasswordField pf_password1;
    private javax.swing.JTextField tf_correo;
    private javax.swing.JTextField tf_correo1;
    private javax.swing.JTextField tf_crearPassword;
    private javax.swing.JTextField tf_crearPassword1;
    private javax.swing.JTextField tf_crearUsuario;
    private javax.swing.JTextField tf_crearUsuario1;
    private javax.swing.JTextField tf_nombreOG;
    private javax.swing.JTextField tf_nombreUsuario;
    private javax.swing.JTextField tf_nombreUsuario1;
    private javax.swing.JTabbedPane tp_jugador;
    private javax.swing.JTabbedPane tp_main;
    // End of variables declaration//GEN-END:variables
}
